# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift

on:
  pull_request:
    branches: 
           - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: install dependencies
      working-directory: ./mock-weather-server
      run: npm ci
    - name: run server
      working-directory: ./mock-weather-server
      run: pm2 start app.js
    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v

